# meta file for adminer
---
galaxy_info:
  author: Soeren Oehding
  company: SO_DSGN
  description: Submodule to install PimpMyLog log analyzer
  license: MIT
  min_ansible_version: 1.9.6
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
    - web
    - development
    - log
dependencies: []
