---
- name: PHP | Place PHP {{ item }} apache2 configuration file in place.
  become: yes
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ item }}/apache2/php.ini"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ php.versions }}"

- name: PHP | Place PHP {{ item }} cgi configuration file in place.
  become: yes
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ item }}/cgi/php.ini"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ php.versions }}"

- name: PHP | Place PHP {{ item }} cli configuration file in place.
  become: yes
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ item }}/cli/php.ini"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ php.versions }}"

- name: PHP | Ensures /var/log/php/ dir exists
  become: yes
  file:
    path=/var/log/php/
    recurse=yes
    state=directory

- name: PHP | Create initial log files
  become: yes
  file:
    state: touch
    path: "{{ item }}"
    owner: vagrant
    group: vagrant
    mode: 0664
  with_items:
    - "/var/log/php/error.log"