---
- name: Cleanup - Remove old PHP Versions
  become: true
  apt: pkg=php5-common state=absent purge=yes autoremove=yes

- name: Add ppa Repository
  become: true
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  become: true
  apt: update_cache=yes

- name: Install PHP Versions
  become: true
  apt: pkg=php{{ item }} state=latest
  with_items: "{{ php.versions }}"
  when: php.versions is defined

- name: Install PHP Packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items: "{{ php.packages }}"
  when: php.packages is defined

- include: configure.yml