---
- name: start apache
  service: name=apache2 state=started
  become: yes

- name: restart apache
  action: service name=apache2 state=restarted
  become: yes

- name: reload apache
  service: name=apache2 state=reloaded
  become: yes