---
  - name: Apache2 | ensure apache is installed
    apt: name=apache2 state=present

  - name: Apache2 | enabled mod_actions
    apache2_module: name=actions state=present
    notify:
    - restart apache

  - name: Apache2 | enabled mod_fcgi
    apache2_module: name=fastcgi state=present
    notify:
    - restart apache

  - name: Apache2 | enabled mod_rewrite
    apache2_module: name=rewrite state=present
    notify:
    - restart apache

  - name: Apache2 | enabled mod_headers
    apache2_module: name=headers state=present
    notify:
    - restart apache

  - name: Apache2 | enabled mod_proxy
    apache2_module: name=proxy state=present
    notify:
    - restart apache

  - name: Apache2 | remove default index
    file: path=/var/www/html/index.html state=absent

  - name: Apache2 | remove default vhosts
    file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

  - name: Apache2 | Copy files
    copy: src=fqdn.conf dest=/etc/apache2/conf-enabled/fqdn.conf

  - name: Apache2 | Copy files
    copy: src=nosendfile.conf dest=/etc/apache2/conf-enabled/nosendfile.conf
    notify: 
    - restart apache

  - name: Apache2 | make sure apache is running
    action: service name=apache2 state=started enabled=true