---
  - name: Apache2 | ensure apache is installed
    apt: name=apache2 state=present
    become: yes

  - name: Apache2 | enabled mod_autoindex
    apache2_module: name=autoindex state=present
    become: yes
    notify:
    - restart apache

  - name: Apache2 | enabled mod_actions
    apache2_module: name=actions state=present
    become: yes
    notify:
    - restart apache

  - name: Apache2 | enabled mod_rewrite
    apache2_module: name=rewrite state=present
    become: yes
    notify:
    - restart apache

  - name: Apache2 | enabled mod_headers
    apache2_module: name=headers state=present
    become: yes
    notify:
    - restart apache

  - name: Apache2 | enabled mod_proxy
    apache2_module: name=proxy state=present
    become: yes
    notify:
    - restart apache

  - name: Apache2 | Set /var/lock/apache2 owner
    file: path=/var/lock/apache2 recurse=yes state=directory group={{ apache.group }} owner={{ apache.user }}
    become: yes

  - name: Apache2 | Set Apache user and group
    lineinfile: >
      dest=/etc/apache2/envvars
      regexp="{{ item.key }}"
      line="{{ item.value }}"
      state=present
    with_items:
     - { key: "^export APACHE_RUN_USER=", value: "export APACHE_RUN_USER={{ apache.user }}" }
     - { key: "^export APACHE_RUN_GROUP=", value: "export APACHE_RUN_GROUP={{ apache.group }}" }
    notify:
     - restart apache
    become: yes

  - name: Apache2 | remove default index
    become: yes
    file: path=/var/www/html/index.html state=absent

  - name: Apache2 | remove default vhosts
    become: yes
    file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

  - name: Apache2 | Copy files
    become: yes
    copy: src=fqdn.conf dest=/etc/apache2/conf-enabled/fqdn.conf

  - name: Apache2 | Copy files
    become: yes
    copy: src=nosendfile.conf dest=/etc/apache2/conf-enabled/nosendfile.conf
    notify: 
    - restart apache

  - name: Apache2 | make sure apache is running
    action: service name=apache2 state=started enabled=true
    become: yes